title: Matthew Dodds
email: matthewrusselldodds@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about software, design patterns, frameworks, interesting problems,
  and all things technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matthewdodds.com" # the base hostname & protocol for your site
twitter_username: Dodds_M
github_username:  MatthewRDodds

# Build settings
highlighter: pygments
# highlighter: rouge
markdown: kramdown
permalink: pretty
