title: Matthew Russell Dodds
email: matthewrusselldodds@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack Ruby on Rails Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matthewdodds.com" # the base hostname & protocol for your site
twitter_username: Dodds_M
github_username:  MatthewRDodds

# Build settings
# highlighter: pygments
highlighter: rouge
markdown: kramdown
permalink: pretty
