title: Matthew Russell Dodds | Freelance Software Developer
email: matthewrusselldodds@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matthewdodds.com" # the base hostname & protocol for your site
twitter_username: Dodds_M
github_username:  MatthewRDodds

# Build settings
# highlighter: pygments
highlighter: rouge
markdown: kramdown
permalink: pretty
